// To lerance: 1 3 5
// Ab sorption: 2 4 15
// Ap praisal: 6* 7 9 10 11 12 
// Re gultion 8 13 14
let finalQuestions = [
    {
      "personalityTrait": "TO",
      "questionNumber": 1,
      "questionDetails": "Feeling distressed or upset is unbearable to me",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "AB",
      "questionNumber": 2,
      "questionDetails": "When I feel distressed or upset, all I can think about is how bad I feel",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "TO",
      "questionNumber": 3,
      "questionDetails": "I can’t handle feeling bad or distressed",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "AB",
      "questionNumber": 4,
      "questionDetails": "My feelings of distress are so intense that they completely take over. 5.There’s nothing worse than feeling distressed or upset",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "TO",
      "questionNumber": 5,
      "questionDetails": "There’s nothing worse than feeling distressed or upset",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "AP",
      "questionNumber": 6,
      "questionDetails": "I can tolerate being distressed or upset",
      "answerA": "Strongly Agree",
      "answerAPoints": 5,
      "answerB": "Mildly Agree",
      "answerBPoints": 4,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 2,
      "answerE": "Strongly Disagree",
      "answerEPoints": 1
    },
    {
      "personalityTrait": "AP",
      "questionNumber": 7,
      "questionDetails": "My feelings of being distressed or upset are not acceptable",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "RE",
      "questionNumber": 8,
      "questionDetails": "I’ll do anything to avoid feeling upset or distressed",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "AP",
      "questionNumber": 9,
      "questionDetails": "Other people seem to be able to tolerate feeling distressed or upset better than I can",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "AP",
      "questionNumber": 10,
      "questionDetails": "Being distressed or upset is always a major ordeal for me",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "AP",
      "questionNumber": 11,
      "questionDetails": "I am ashamed of myself when I feel distressed or upset",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "AP",
      "questionNumber": 12,
      "questionDetails": "My feelings of distressed or being upset scare me",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "RE",
      "questionNumber": 13,
      "questionDetails": "I’ll do anything to stop feeling distressed or upset",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "RE",
      "questionNumber": 14,
      "questionDetails": "When I feel distressed or upset, I must do something about it immediately",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    },
    {
      "personalityTrait": "AB",
      "questionNumber": 15,
      "questionDetails": "When I feel distressed or upset, I cannot help but concentrate on how bad the distress actually feels",
      "answerA": "Strongly Agree",
      "answerAPoints": 1,
      "answerB": "Mildly Agree",
      "answerBPoints": 2,
      "answerC": "Agree and Disagree Equally",
      "answerCPoints": 3,
      "answerD": "Mildly Disagree",
      "answerDPoints": 4,
      "answerE": "Strongly Disagree",
      "answerEPoints": 5
    }
  ]