let finalQuestions = [
    {
      "personalityTrait": "AUTO",
      "questionNumber": 1,
      "questionDetails": "I am not afraid to voice my opinions, even when they are in opposition to the opinions of most people.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "ENVMAS",
      "questionNumber": 2,
      "questionDetails": "In general, I feel I am in charge of the situation in which I live.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "PERSGROW",
      "questionNumber": 3,
      "questionDetails": "I am not interested in activities that will expand my horizons.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "POSIREL",
      "questionNumber": 4,
      "questionDetails": "Most people see me as loving and affectionate.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "PIL",
      "questionNumber": 5,
      "questionDetails": "I live life one day at a time and don't really think about the future.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "SELFAC",
      "questionNumber": 6,
      "questionDetails": "When I look at the story of my life, I am pleased with how things have turned out.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "AUTO",
      "questionNumber": 7,
      "questionDetails": "My decisions are not usually influenced by what everyone else is doing.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "ENVMAS",
      "questionNumber": 8,
      "questionDetails": "The demands of everyday life often get me down.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "PERSGROW",
      "questionNumber": 9,
      "questionDetails": "I think it is important to have new experiences that challenge how you think about yourself and the world.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "POSIREL",
      "questionNumber": 10,
      "questionDetails": "Maintaining close relationships has been difficult and frustrating for me.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "PIL",
      "questionNumber": 11,
      "questionDetails": "I have a sense of direction and purpose in life.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "SELFAC",
      "questionNumber": 12,
      "questionDetails": "In general, I feel confident and positive about myself.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "AUTO",
      "questionNumber": 13,
      "questionDetails": "I tend to worry about what other people think of me.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "ENVMAS",
      "questionNumber": 14,
      "questionDetails": "I do not fit very well with the people and the community around me.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "PERSGROW",
      "questionNumber": 15,
      "questionDetails": "When I think about it, I haven't really improved much as a person over the years.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "POSIREL",
      "questionNumber": 16,
      "questionDetails": "I often feel lonely because I have few close friends with whom to share my concerns.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "PIL",
      "questionNumber": 17,
      "questionDetails": "My daily activities often seem trivial and unimportant to me.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "SELFAC",
      "questionNumber": 18,
      "questionDetails": "I feel like many of the people I know have gotten more out of life than I have.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "AUTO",
      "questionNumber": 19,
      "questionDetails": "I tend to be influenced by people with strong opinions.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "ENVMAS",
      "questionNumber": 20,
      "questionDetails": "I am quite good at managing the many responsibilities of my daily life.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "PERSGROW",
      "questionNumber": 21,
      "questionDetails": "I have the sense that I have developed a lot as a person over time.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "POSIREL",
      "questionNumber": 22,
      "questionDetails": "I enjoy personal and mutual conversations with family members or friends.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "PIL",
      "questionNumber": 23,
      "questionDetails": "I don't have a good sense of what it is I'm trying to accomplish in life.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "SELFAC",
      "questionNumber": 24,
      "questionDetails": "I like most aspects of my personality.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "AUTO",
      "questionNumber": 25,
      "questionDetails": "I have confidence in my opinions, even if they are contrary to the general consensus.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "ENVMAS",
      "questionNumber": 26,
      "questionDetails": "I often feel overwhelmed by my responsibilities.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "PERSGROW",
      "questionNumber": 27,
      "questionDetails": "I do not enjoy being in new situations that require me to change my old familiar ways of doing things.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "POSIREL",
      "questionNumber": 28,
      "questionDetails": "People would describe me as a giving person, willing to share my time with others.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "PIL",
      "questionNumber": 29,
      "questionDetails": "I enjoy making plans for the future and working to make them a reality.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "SELFAC",
      "questionNumber": 30,
      "questionDetails": "In many ways, I feel disappointed about my achievements in life.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "AUTO",
      "questionNumber": 31,
      "questionDetails": "It's difficult for me to voice my own opinions on controversial matters.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "ENVMAS",
      "questionNumber": 32,
      "questionDetails": "I have difficulty arranging my life in a way that is satisfying to me.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "PERSGROW",
      "questionNumber": 33,
      "questionDetails": "For me, life has been a continuous process of learning, changing, and growth.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "POSIREL",
      "questionNumber": 34,
      "questionDetails": "I have not experienced many warm and trusting relationships with others.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "PIL",
      "questionNumber": 35,
      "questionDetails": "Some people wander aimlessly through life, but I am not one of them.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "SELFAC",
      "questionNumber": 36,
      "questionDetails": "My attitude about myself is probably not as positive as most people feel about themselves.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "AUTO",
      "questionNumber": 37,
      "questionDetails": "I judge myself by what I think is important, not by the values of what others think is important.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "ENVMAS",
      "questionNumber": 38,
      "questionDetails": "I have been able to builf a home and a lifestyle for myself that is much to my liking.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "PERSGROW",
      "questionNumber": 39,
      "questionDetails": "I gave up trying to make big improvements or changes in my life a long time ago.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "POSIREL",
      "questionNumber": 40,
      "questionDetails": "I know that I can trust my friends, and they know they can trust me.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    },
    {
      "personalityTrait": "PIL",
      "questionNumber": 41,
      "questionDetails": "I sometimes feel as if I've done all there is to do in my life.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 6,
      "answerB": "Disagree",
      "answerBPoints": 5,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 4,
      "answerD": "Somewhat Agree",
      "answerDPoints": 3,
      "answerE": "Agree",
      "answerEPoints": 2,
      "answerF": "Strongly Agree",
      "answerFPoints": 1
    },
    {
      "personalityTrait": "SELFAC",
      "questionNumber": 42,
      "questionDetails": "When I compare myself to friends and acquaintances, it makes me feel good about who I am.",
      "answerA": "Strongly Disagree",
      "answerAPoints": 1,
      "answerB": "Disagree",
      "answerBPoints": 2,
      "answerC": "Somewhat Disagree",
      "answerCPoints": 3,
      "answerD": "Somewhat Agree",
      "answerDPoints": 4,
      "answerE": "Agree",
      "answerEPoints": 5,
      "answerF": "Strongly Agree",
      "answerFPoints": 6
    }
  ]