let finalQuestions = [
  {
    "personalityTrait": "Z",
    "questionNumber": 1,
    "questionDetails": "I have the instructions for this test clearly in my mind",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 0,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Z",
    "questionNumber": 2,
    "questionDetails": "I am ready to answer each question as truthfully as possible",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 0,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "A",
    "questionNumber": 3,
    "questionDetails": "I would rather have a house:",
    "answerA": "in a sociable suburb,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 2,
    "answerC": "alone in the deep woods.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "C",
    "questionNumber": 4,
    "questionDetails": "I can find enough energy to face my difficulties",
    "answerA": "always,",
    "answerAPoints": 2,
    "answerB": "generally,",
    "answerBPoints": 1,
    "answerC": "seldom",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "C",
    "questionNumber": 5,
    "questionDetails": "I feel a bit nervous of wild animals even when they are in strong cages",
    "answerA": "yes (true),",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no (false)",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "E",
    "questionNumber": 6,
    "questionDetails": "I hold back from criticizing people and their ideas",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "sometimes,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "E",
    "questionNumber": 7,
    "questionDetails": "I make smart, sarcastic remarks to people if I think they deserve it.",
    "answerA": "generally,",
    "answerAPoints": 2,
    "answerB": "sometimes,",
    "answerBPoints": 1,
    "answerC": "never.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "F",
    "questionNumber": 8,
    "questionDetails": "I prefer semiclassical music to popular tunes.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "G",
    "questionNumber": 9,
    "questionDetails": "If I saw two neighbor's children fighting, I would:",
    "answerA": "leave them to settle it,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "reason with them.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "H",
    "questionNumber": 10,
    "questionDetails": "On social occasions I:",
    "answerA": "readily come forward,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "prefer to stay quietly in the background.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "I",
    "questionNumber": 11,
    "questionDetails": "It would be more interesting to be:",
    "answerA": "a construction engineer",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "a writer of plays.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "I",
    "questionNumber": 12,
    "questionDetails": "I would rather shop in the street to watch an artist painting than listen to some people having a quarrel",
    "answerA": "true,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "L",
    "questionNumber": 13,
    "questionDetails": "I can generally put up with conceited people, even though they brag or show they think too well of themselves.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "M",
    "questionNumber": 14,
    "questionDetails": "You can almost always notice on a man's face when he is dishonest.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "M",
    "questionNumber": 15,
    "questionDetails": "It would be good for everyone if vacations (holidays) were longer and everyone had to take them.",
    "answerA": "agree,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "disagree.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "N",
    "questionNumber": 16,
    "questionDetails": "I would rather take the gamble of a job with possibly large but uneven earnings, than one with a steady, small salary.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "N",
    "questionNumber": 17,
    "questionDetails": "I talk about my feelings:",
    "answerA": "only if necessary,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "readily, whenever I have a chance.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "O",
    "questionNumber": 18,
    "questionDetails": "Once in a while I have a sense of vague danger or sudden dread for reasons that I do not understand.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "O",
    "questionNumber": 19,
    "questionDetails": "When criticized wrongly for something I did not do, I:",
    "answerA": "have no feeling of guilt,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "still feel a bit guilty.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q1",
    "questionNumber": 20,
    "questionDetails": "Money can buy almost everything.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q1",
    "questionNumber": 21,
    "questionDetails": "My decisions are governed more by my:",
    "answerA": "heart,",
    "answerAPoints": 0,
    "answerB": "feelings and reason equally,",
    "answerBPoints": 1,
    "answerC": "head.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q2",
    "questionNumber": 22,
    "questionDetails": "Most people would be happier if they lived more with their fellows and did the same things as others.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q3",
    "questionNumber": 23,
    "questionDetails": "I occasionally get puzzled, when looking in a mirror, as to which is my right and left.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q3",
    "questionNumber": 24,
    "questionDetails": "When talking, I like:",
    "answerA": "to say things, just as they occur to me,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "to get my thoughts well organized first.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 25,
    "questionDetails": "When something really makes me furious, find I calm down again quite quickly.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "A",
    "questionNumber": 26,
    "questionDetails": "With the same hours and pay, it would be more interesting to be:",
    "answerA": "a carpenter or cook,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "a waiter in a good restaurant.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "A",
    "questionNumber": 27,
    "questionDetails": "I have been elected to:",
    "answerA": "only a few offices,",
    "answerAPoints": 0,
    "answerB": "several,",
    "answerBPoints": 1,
    "answerC": "many offices.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "B",
    "questionNumber": 28,
    "questionDetails": "Spade\" is to \"dig\" as \"knife\" is to:",
    "answerA": "sharp,",
    "answerAPoints": 0,
    "answerB": "cut,",
    "answerBPoints": 1,
    "answerC": "point.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "C",
    "questionNumber": 29,
    "questionDetails": "I sometimes can't get to sleep because an idea keeps running through my mind",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "C",
    "questionNumber": 30,
    "questionDetails": "In my personali life I reach the goals I set, almost all the time",
    "answerA": "true,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "E",
    "questionNumber": 31,
    "questionDetails": "An out-dated law should be changed:",
    "answerA": "only after considerable discussion",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "promptly.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "E",
    "questionNumber": 32,
    "questionDetails": "I am uncomfortable when I work on a project requiring quick action affecting others.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "F",
    "questionNumber": 33,
    "questionDetails": "Most of the people I know would rate me as an amusing talker.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "G",
    "questionNumber": 34,
    "questionDetails": "When I see \"sloppy\", untidy people, I:",
    "answerA": "just accept it,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "get disgusted and annoyed.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "H",
    "questionNumber": 35,
    "questionDetails": "I get slightly embarrassed if I suddenly become the focus of attention in a social group",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "H",
    "questionNumber": 36,
    "questionDetails": "I am always glad to join a large gathering, for example, a party, dance, or public meeting.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "I",
    "questionNumber": 37,
    "questionDetails": "In school I preferred (or prefer):",
    "answerA": "music,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "handwork and crafts.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "L",
    "questionNumber": 38,
    "questionDetails": "When I have been put in charge of something, I insist that my instructions are followed or else I resign.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "sometimes,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "M",
    "questionNumber": 39,
    "questionDetails": "For parents, it is more important to:",
    "answerA": "help their children develop their affections,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "teach their children how to control emotions.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "M",
    "questionNumber": 40,
    "questionDetails": "In a group task I would rather:",
    "answerA": "try to improve arrangements,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "keep the records and see that rules are followed.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "N",
    "questionNumber": 41,
    "questionDetails": "I feel a need every now and then to engage in a tough physical activity.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "N",
    "questionNumber": 42,
    "questionDetails": "I would rather mix with polite people than rough, rebellious individuals.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "O",
    "questionNumber": 43,
    "questionDetails": "I feel terribly dejected when people criticize me in a group.",
    "answerA": "true,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "O",
    "questionNumber": 44,
    "questionDetails": "If I am called in by my boss, I:",
    "answerA": "make it a chance to ask for something I want,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "fear I've done something wrong.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q1",
    "questionNumber": 45,
    "questionDetails": "What this world needs is:",
    "answerA": "more steady and \"solid\" citizens,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "more \"idealists\" with plans for a better world.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q1",
    "questionNumber": 46,
    "questionDetails": "I am always keenly aware of attempts at propaganda in things I read.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q2",
    "questionNumber": 47,
    "questionDetails": "As a teenager, I joined in school sports:",
    "answerA": "occasionally,",
    "answerAPoints": 2,
    "answerB": "fairly often,",
    "answerBPoints": 1,
    "answerC": "a great deal.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q3",
    "questionNumber": 48,
    "questionDetails": "I keep my room well organized, with things in known places almost all the time.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 49,
    "questionDetails": "I sometimes get in a state of tension and turmoil as I think of the day's happenings.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 50,
    "questionDetails": "I sometimes doubt whether people I am talking to are really interested in what I am saying.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "A",
    "questionNumber": 51,
    "questionDetails": "If I had to chose I would rather be:",
    "answerA": "a forester,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "a high school teacher.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "A",
    "questionNumber": 52,
    "questionDetails": "For special holidays and birthdays, I:",
    "answerA": "like to give personal presents,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "feel that buying presents is a bit of a nuisance",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "B",
    "questionNumber": 53,
    "questionDetails": "Tired\" is to \"work\" as \"proud\" is to:",
    "answerA": "smile,",
    "answerAPoints": 0,
    "answerB": "success,",
    "answerBPoints": 1,
    "answerC": "happy.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "B",
    "questionNumber": 54,
    "questionDetails": "Which of the following items is different in kind from the others?",
    "answerA": "candle,",
    "answerAPoints": 0,
    "answerB": "moon,",
    "answerBPoints": 1,
    "answerC": "electric light.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "C",
    "questionNumber": 55,
    "questionDetails": "I have been let down by my friends",
    "answerA": "hardly ever,",
    "answerAPoints": 2,
    "answerB": "occasionally,",
    "answerBPoints": 1,
    "answerC": "quite a lot.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "E",
    "questionNumber": 56,
    "questionDetails": "I have some characteristics in which I feel definitely superior to most people.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "E",
    "questionNumber": 57,
    "questionDetails": "When I get upset, I try hard to hide my feelings from others.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "F",
    "questionNumber": 58,
    "questionDetails": "I like to go out to a show or entertainment:",
    "answerA": "more than once a week (more than average)",
    "answerAPoints": 2,
    "answerB": "about once a week (average)",
    "answerBPoints": 1,
    "answerC": "less than once a week (less than average)",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "G",
    "questionNumber": 59,
    "questionDetails": "I think that plenty of freedom is more important than good manners and respect for the law.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "H",
    "questionNumber": 60,
    "questionDetails": "I tend to keep quiet in the presence of senior persons (people of greater experience, age, or rank).",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "H",
    "questionNumber": 61,
    "questionDetails": "I find it hard to address or recite to a large group.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "I",
    "questionNumber": 62,
    "questionDetails": "I have a good sense of direction (find it easy to tell which is North, South, East, or West) when in a strange place.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "L",
    "questionNumber": 63,
    "questionDetails": "If someone got mad at me, I would:",
    "answerA": "try to calm him down,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "get irritated.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Z",
    "questionNumber": 64,
    "questionDetails": "When I read an unfair magazine article, I am more inclined to forget it than to feel like \"hitting back.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 0,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "M",
    "questionNumber": 65,
    "questionDetails": "My memory tends to drop a lot of unimportant trivial things for example, names of streets or stores in town.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "N",
    "questionNumber": 66,
    "questionDetails": "I could enjoy the life of an animal doctor, handling disease and surgery of animals.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "N",
    "questionNumber": 67,
    "questionDetails": "I eat my food with gusto, not always so carefully and properly as some people.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "O",
    "questionNumber": 68,
    "questionDetails": "There are times when I don't feel in the right mood to see anyone.",
    "answerA": "very rarely,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "quite often.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "O",
    "questionNumber": 69,
    "questionDetails": "People sometimes warn me that I show my excitement in voice and manner too obviously.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q1",
    "questionNumber": 70,
    "questionDetails": "As a teenager, if I differed in opinion from my parents, I usually:",
    "answerA": "kept my own opinion,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "accepted their authority.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q2",
    "questionNumber": 71,
    "questionDetails": "I would prefer to have an office of my own not sharing it with another person.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q2",
    "questionNumber": 72,
    "questionDetails": "I would rather enjoy life quietly in my own way than be admired for my achievements.",
    "answerA": "true,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q3",
    "questionNumber": 73,
    "questionDetails": "I feel mature in most things.",
    "answerA": "true,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 74,
    "questionDetails": "I find myself upset rather than helped by the kind of criticism that many people offer one",
    "answerA": "often,",
    "answerAPoints": 2,
    "answerB": "occasionally,",
    "answerBPoints": 1,
    "answerC": "never.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 75,
    "questionDetails": "I am always able to keep the exporession of my feelings under exact control.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "A",
    "questionNumber": 76,
    "questionDetails": "In starting a useful invention, I would prefer:",
    "answerA": "working on it in the laboratory,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "selling it to people.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "B",
    "questionNumber": 77,
    "questionDetails": "Surprise\" is to \"strange\" as \"fear is to:",
    "answerA": "brave,",
    "answerAPoints": 0,
    "answerB": "anxious,",
    "answerBPoints": 0,
    "answerC": "terrible.",
    "answerCPoints": 1
  },
  {
    "personalityTrait": "B",
    "questionNumber": 78,
    "questionDetails": "Which of the following is not in the same class as the others?",
    "answerA": "3 upon 7",
    "answerAPoints": 0,
    "answerB": "3 upon 9",
    "answerBPoints": 1,
    "answerC": "3 upon 11",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "C",
    "questionNumber": 79,
    "questionDetails": "Some people seem to ignore or avoid me. Although I don't know why",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "C",
    "questionNumber": 80,
    "questionDetails": "People treat me less reasonably than my good intentions deserve.",
    "answerA": "often,",
    "answerAPoints": 0,
    "answerB": "ocassionally,",
    "answerBPoints": 1,
    "answerC": "never.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "E",
    "questionNumber": 81,
    "questionDetails": "The use of foul language, even when it is not in a mixed group of men and women, still disgusts me.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "F",
    "questionNumber": 82,
    "questionDetails": "I have decidedly fewer friends than most people.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "F",
    "questionNumber": 83,
    "questionDetails": "I would hate to be where there wouldn't be a lot of people to talk to.",
    "answerA": "true,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "G",
    "questionNumber": 84,
    "questionDetails": "People sometimes call me careless, even though they think I'm a likable person.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "H",
    "questionNumber": 85,
    "questionDetails": "Stage-fright\" in various social situations is something I have experienced:",
    "answerA": "quite often,",
    "answerAPoints": 0,
    "answerB": "occasionally,",
    "answerBPoints": 1,
    "answerC": "hardly ever.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "H",
    "questionNumber": 86,
    "questionDetails": "When I am in a small group, I am content to sit back and let others do most of the talking.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "I",
    "questionNumber": 87,
    "questionDetails": "I prefer reading:",
    "answerA": "a realistic account of military or political battles,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "a sensitive, imaginative novel.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "L",
    "questionNumber": 88,
    "questionDetails": "When bossy people try to \"push me around\", I do just the opposite of what they wish.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "L",
    "questionNumber": 89,
    "questionDetails": "Business superiors or members of my family, as a rule, find fault with me only when there is real cause.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "M",
    "questionNumber": 90,
    "questionDetails": "In streets or stores, I dislike the way some persons stare at people.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "M",
    "questionNumber": 91,
    "questionDetails": "On a long journey, I would prefer to:",
    "answerA": "read something profound, but interesting,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "pass the time talking casually with a fellow passenger.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "N",
    "questionNumber": 92,
    "questionDetails": "In a situation which may become dangerous, I believe in making a fuss and speaking up even if calmness and politeness are lost.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "O",
    "questionNumber": 93,
    "questionDetails": "If acquaintances treat me badly and show they dislike me:",
    "answerA": "it doesn't upset me a bit,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "I tend to get downhearted.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "O",
    "questionNumber": 94,
    "questionDetails": "I find it embarrassing to have praise or compliments bestowed on me.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q1",
    "questionNumber": 95,
    "questionDetails": "I would rather have a job with:",
    "answerA": "a fixed, certain salary,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "a larger salary, which depended on my constantly persuading people I am worth it.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q2",
    "questionNumber": 96,
    "questionDetails": "To keep informed, I like:",
    "answerA": "to discuss issues with people,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "to rely on the actual news reports.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q2",
    "questionNumber": 97,
    "questionDetails": "I like to take an active part in social affairs, committee work, etc.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q3",
    "questionNumber": 98,
    "questionDetails": "In carrying out a task, I am not satisfied unless even the minor details are given close attention.",
    "answerA": "true,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 99,
    "questionDetails": "Quite small setbacks occasionally irritate me too much.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 100,
    "questionDetails": "I am always a sound sleeper, never walking or talking in my sleep.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "A",
    "questionNumber": 101,
    "questionDetails": "It would be more interesting to work in a business:",
    "answerA": "talking to customers,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "keeping office accounts and records.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "B",
    "questionNumber": 102,
    "questionDetails": "Size\" is to \"length\" as \"dishonest\" is to",
    "answerA": "prison,",
    "answerAPoints": 0,
    "answerB": "sin,",
    "answerBPoints": 0,
    "answerC": "stealing.",
    "answerCPoints": 1
  },
  {
    "personalityTrait": "B",
    "questionNumber": 103,
    "questionDetails": "AB is to dc as SR is to:",
    "answerA": "qp,",
    "answerAPoints": 0,
    "answerB": "pq,",
    "answerBPoints": 1,
    "answerC": "tu.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "C",
    "questionNumber": 104,
    "questionDetails": "When people are unreasonable, I just:",
    "answerA": "keep quiet",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "despise them.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "C",
    "questionNumber": 105,
    "questionDetails": "If people talk loudly while I am listening to music, I:",
    "answerA": "can keep my mind on the music and not be bothered,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "find it spoils my enjoyment and annoys me.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "E",
    "questionNumber": 106,
    "questionDetails": "I think I am better described as:",
    "answerA": "polite and quiet,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "forceful.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "F",
    "questionNumber": 107,
    "questionDetails": "I attend social functions only when I have to, and stay away any other time.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "F",
    "questionNumber": 108,
    "questionDetails": "To be cautious and expect little is better than to be happy at heart, always expecting success.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "G",
    "questionNumber": 109,
    "questionDetails": "In thinking of difficulties in my work, I:",
    "answerA": "try to plan ahead, before I meet them,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "assume I can handle them when they come.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "H",
    "questionNumber": 110,
    "questionDetails": "I find it easy to mingle among people at a social gathering.",
    "answerA": "true,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "H",
    "questionNumber": 111,
    "questionDetails": "When a bit of diplomacy and persuasion are needed to get people moving, I am generally the one asked to do it.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "I",
    "questionNumber": 112,
    "questionDetails": "It would be more interesting to be:",
    "answerA": "a guidance worker helping young people find jobs,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "a manager in efficiency engineering.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "L",
    "questionNumber": 113,
    "questionDetails": "If I am quite sure that a person is unjust or behaving selfishly, I show him up, even if it takes some trouble.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "L",
    "questionNumber": 114,
    "questionDetails": "I sometimes make foolish remarks in fun, just to surprise people and see what they will say.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "M",
    "questionNumber": 115,
    "questionDetails": "I would enjoy being a newspaper writer on drama, concerts, opera, etc.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "M",
    "questionNumber": 116,
    "questionDetails": "I never feel the urge to doodle and fidget when kept sitting still at a meeting.",
    "answerA": "true,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "N",
    "questionNumber": 117,
    "questionDetails": "If someone tells me something which I know is wrong, I am more likely to say to myself:",
    "answerA": "He is a liar,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "Apparently he is misinformed.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "O",
    "questionNumber": 118,
    "questionDetails": "I feel some punishment is coming to me even when I have done nothing wrong.",
    "answerA": "often,",
    "answerAPoints": 2,
    "answerB": "occasionally,",
    "answerBPoints": 1,
    "answerC": "never.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "O",
    "questionNumber": 119,
    "questionDetails": "The idea that sickness comes as much from mental as physical causes is much exaggerated.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q1",
    "questionNumber": 120,
    "questionDetails": "The pomp and splendor of any big state ceremony are things which should be preserved.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q2",
    "questionNumber": 121,
    "questionDetails": "It bothers me if people think I am being too unconventional or odd.",
    "answerA": "a lor,",
    "answerAPoints": 0,
    "answerB": "somewhat,",
    "answerBPoints": 1,
    "answerC": "not at all.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q2",
    "questionNumber": 122,
    "questionDetails": "In constructing something I would rather work:",
    "answerA": "with a committee,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "on my own.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q3",
    "questionNumber": 123,
    "questionDetails": "I have periods when it's hard to stop a mood of self-pity.",
    "answerA": "often,",
    "answerAPoints": 0,
    "answerB": "occasionally,",
    "answerBPoints": 1,
    "answerC": "never.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 124,
    "questionDetails": "Often I get angry with people too quickly.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 125,
    "questionDetails": "I can always change old habits without difficulty and without slipping back.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "A",
    "questionNumber": 126,
    "questionDetails": "If the earnings were the same, I would rather be:",
    "answerA": "a lawyer,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "a navigator or pilot.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "B",
    "questionNumber": 127,
    "questionDetails": "Better\" is to \"worst\" as \"slower\" is to:",
    "answerA": "fast,",
    "answerAPoints": 0,
    "answerB": "best,",
    "answerBPoints": 0,
    "answerC": "quickest.",
    "answerCPoints": 1
  },
  {
    "personalityTrait": "B",
    "questionNumber": 128,
    "questionDetails": "Which of the following should come next at the end of this row of letters: xooooxxoooxxx?",
    "answerA": "oxxx,",
    "answerAPoints": 0,
    "answerB": "ooxx,",
    "answerBPoints": 1,
    "answerC": "xooo.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "C",
    "questionNumber": 129,
    "questionDetails": "When the time comes for something I have planned and looked forward to, I occasionally do not feel up to going.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "C",
    "questionNumber": 130,
    "questionDetails": "I can work carefully on most things without being bothered by people making a lot of noise around me.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "E",
    "questionNumber": 131,
    "questionDetails": "I occasionally tell strangers things that seem to me important, regardless of whether they ask about them.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "F",
    "questionNumber": 132,
    "questionDetails": "I spend much of my spare time talking with friends about social events enjoyed in the past.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "F",
    "questionNumber": 133,
    "questionDetails": "I enjoy doing \"daring\", foolhardy things \"just for fun.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "G",
    "questionNumber": 134,
    "questionDetails": "I find the sight of an untidy room very annoying.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "H",
    "questionNumber": 135,
    "questionDetails": "I consider myself a very sociable, outgoing person.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "H",
    "questionNumber": 136,
    "questionDetails": "In social contacts I:",
    "answerA": "show my emotions as I wish,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "keep my emotions to myself.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "I",
    "questionNumber": 137,
    "questionDetails": "I enjoy music that is:",
    "answerA": "light, dry and brisk,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "emotional and sentimental.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "I",
    "questionNumber": 138,
    "questionDetails": "I admire the beauty of a poem more than that of a well-made gun.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "L",
    "questionNumber": 139,
    "questionDetails": "If a good remark of mine is passed by, I:",
    "answerA": "let it go,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "give people a chance to hear it again.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "M",
    "questionNumber": 140,
    "questionDetails": "I would like to work as a probation officer with criminals on parole.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "M",
    "questionNumber": 141,
    "questionDetails": "One should be careful about mixing with all kinds of strangers, since there are dangers of infection and so on.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "N",
    "questionNumber": 142,
    "questionDetails": "In travelling abroad, I would rather go on an expertly conducted tour than plan by myself the places I wish to visit.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "O",
    "questionNumber": 143,
    "questionDetails": "I am properly regarded as only a plodding, half-successful person.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "O",
    "questionNumber": 144,
    "questionDetails": "If people take advantage of my friendliness, I do not resent it and I soon forget.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q1",
    "questionNumber": 145,
    "questionDetails": "If a heated argument developed between other members taking part in a group discussion, I would:",
    "answerA": "like to see a \"winner,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "wish that it would be smoothed over.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q2",
    "questionNumber": 146,
    "questionDetails": "I like to do my plaanning alone, without interruptions and suggestions from others.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q3",
    "questionNumber": 147,
    "questionDetails": "I sometimes let my actions get swayed by feelings of jealousy.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q3",
    "questionNumber": 148,
    "questionDetails": "I believe firmly \"the boss may not always be right, but he always has the right to be boss.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 149,
    "questionDetails": "I get tense as I think of all the things lying ahead of me.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "sometimes,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 150,
    "questionDetails": "If people shout suggestions when I'm playing a game, it doesn't upset me.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "A",
    "questionNumber": 151,
    "questionDetails": "it would be more interesting to be:",
    "answerA": "an artist,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "a secretary running in a club.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "B",
    "questionNumber": 152,
    "questionDetails": "Which of the following words does not properly belong with the others?",
    "answerA": "any,",
    "answerAPoints": 1,
    "answerB": "some,",
    "answerBPoints": 0,
    "answerC": "most.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "B",
    "questionNumber": 153,
    "questionDetails": "Flame\" is to \"heat\" as \"rose\" is to:",
    "answerA": "thorn",
    "answerAPoints": 0,
    "answerB": "red petals",
    "answerBPoints": 0,
    "answerC": "scent.",
    "answerCPoints": 1
  },
  {
    "personalityTrait": "C",
    "questionNumber": 154,
    "questionDetails": "I have vivid dreams, disturbing my sleep.",
    "answerA": "often,",
    "answerAPoints": 0,
    "answerB": "occassionally,",
    "answerBPoints": 1,
    "answerC": "practically never.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "E",
    "questionNumber": 155,
    "questionDetails": "If the odds are really against something's being a success, I still believe in taking the risk.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "E",
    "questionNumber": 156,
    "questionDetails": "I like it when I know so well what the group has to do that I naturally become the one in command.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "F",
    "questionNumber": 157,
    "questionDetails": "I would rather dress with quiet correctness than with eye-catching personal style.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "F",
    "questionNumber": 158,
    "questionDetails": "An evening with a quiet hobby appeals to me more than a lively party.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "G",
    "questionNumber": 159,
    "questionDetails": "I close my mind to well-meant suggestions of others, even though I know I shouldn't",
    "answerA": "occasionally,",
    "answerAPoints": 0,
    "answerB": "hardly ever,",
    "answerBPoints": 1,
    "answerC": "never.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "G",
    "questionNumber": 160,
    "questionDetails": "I always make it a point. in deciding anything, to refer to basic rules of right and wrong.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "H",
    "questionNumber": 161,
    "questionDetails": "I somewhat dislike having a group watch me at work.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "I",
    "questionNumber": 162,
    "questionDetails": "Because it is not always possible to get things done by gradual, reasonable methods, it is sometimes necessary to use force.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "I",
    "questionNumber": 163,
    "questionDetails": "In school I preferred (or prefer):",
    "answerA": "English,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "mathematics or arithmetic.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "L",
    "questionNumber": 164,
    "questionDetails": "I have sometimes been troubled by people's saying bad things about me behind my back, with no grounds at all.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "M",
    "questionNumber": 165,
    "questionDetails": "Talk with ordinary, habit-bound, conventional people:",
    "answerA": "is often quite interesting and has a lot to it.",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "annoys me because it deals with trifles and lacks depth",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "M",
    "questionNumber": 166,
    "questionDetails": "Some things make me so angry that I find it best not to speak.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "N",
    "questionNumber": 167,
    "questionDetails": "In education, it is more important to:",
    "answerA": "give the child enough affection,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "have the child learn desirable habits and attitudes.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "O",
    "questionNumber": 168,
    "questionDetails": "People regard me as a solid, undisturbed person, unmoved by ups and downs in circumstances.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q1",
    "questionNumber": 169,
    "questionDetails": "I think society should let reason lead it to new customs and throw aside old habits or mere traditions.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q1",
    "questionNumber": 170,
    "questionDetails": "I think it is more important in the modern world to solve:",
    "answerA": "the question of moral purpose,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "the political difficulties.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q2",
    "questionNumber": 171,
    "questionDetails": "I learn better by:",
    "answerA": "reading a well-written book,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "joining a group discussion.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q3",
    "questionNumber": 172,
    "questionDetails": "I like to go my own way instead of acting on approved rules.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "Q3",
    "questionNumber": 173,
    "questionDetails": "I like to wait till I am sure that what I am saying is correct, before I put forth and argument.",
    "answerA": "always,",
    "answerAPoints": 2,
    "answerB": "generally,",
    "answerBPoints": 1,
    "answerC": "only if it's practicable.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 174,
    "questionDetails": "Small things sometimes \"get on my nerves\" unbearably, though I realize they are trivial.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Q4",
    "questionNumber": 175,
    "questionDetails": "I don't often say things on the spur of the moment that I greatly regret.",
    "answerA": "true,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 2
  },
  {
    "personalityTrait": "A",
    "questionNumber": 176,
    "questionDetails": "If asked to work with a charity drive I would",
    "answerA": "accept,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "politely say I'm too busy.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "B",
    "questionNumber": 177,
    "questionDetails": "Which of the following words does not belong with the others?",
    "answerA": "wide,",
    "answerAPoints": 1,
    "answerB": "zigzag,",
    "answerBPoints": 0,
    "answerC": "straight.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "B",
    "questionNumber": 178,
    "questionDetails": "Soon\" is to \"never\" as \"near\" is to:",
    "answerA": "nowhere",
    "answerAPoints": 1,
    "answerB": "far",
    "answerBPoints": 0,
    "answerC": "away",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "C",
    "questionNumber": 179,
    "questionDetails": "If I make an awkward social mistake, I can soon forget it.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "E",
    "questionNumber": 180,
    "questionDetails": "I am always known as an \"idea man\" who almost always puts forward some ideas on a problem.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "E",
    "questionNumber": 181,
    "questionDetails": "I think I am better at showing:",
    "answerA": "nerve in meeting challenges,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "tolerance of other people's wishes.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "F",
    "questionNumber": 182,
    "questionDetails": "I am considered a very enthusiastic person.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "F",
    "questionNumber": 183,
    "questionDetails": "I like a job that offers change, variety, and travel, even if it involves some danger.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "G",
    "questionNumber": 184,
    "questionDetails": "I am a fairly strict person, insisting on always doing things as correctly as possible.",
    "answerA": "true,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "false.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "G",
    "questionNumber": 185,
    "questionDetails": "I enjoy work that requires conscientious, exacting skills.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "in between,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "H",
    "questionNumber": 186,
    "questionDetails": "I am the energetic type who keeps busy.",
    "answerA": "yes,",
    "answerAPoints": 2,
    "answerB": "uncertain,",
    "answerBPoints": 1,
    "answerC": "no.",
    "answerCPoints": 0
  },
  {
    "personalityTrait": "Z",
    "questionNumber": 187,
    "questionDetails": "I am sure there are no questions that I have skipped or failed to answer properly.",
    "answerA": "yes,",
    "answerAPoints": 0,
    "answerB": "uncertain,",
    "answerBPoints": 0,
    "answerC": "no.",
    "answerCPoints": 0
  }
]