let finalQuestions = 
    [
        {
          "personalityTrait": "IND",
          "questionNumber": 1,
          "questionDetails": "I enjoy being unique and different from others in many respects.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 2,
          "questionDetails": "I can talk openly with a person who I meet for the first time, even when this person is much older than I am.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 3,
          "questionDetails": "Even when I strongly disagree with group members, I avoid an argument.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 4,
          "questionDetails": "I have respect for the authority figures with whom I interact.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 5,
          "questionDetails": "I do my own thing, regardless of what others think.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 6,
          "questionDetails": "I respect people who are modest about themselves.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 7,
          "questionDetails": "I feel it is important for me to act as an independent person.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 8,
          "questionDetails": "I will sacrifice my self-interest for the benefit of the group I am in.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 9,
          "questionDetails": "I'd rather say \"No\" directly, than risk being misunderstood.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 10,
          "questionDetails": "Having a lively imagination is important to me.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 11,
          "questionDetails": "I should take into consideration my parents' advice when making education/career plans.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 12,
          "questionDetails": "I feel my fate is intertwined with the fate of those around me.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 13,
          "questionDetails": "I prefer to be direct and fortright when dealing with people I've just met.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 14,
          "questionDetails": "I feel good when I cooperate with others.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 15,
          "questionDetails": "I am comfortable with being singled out for praise or reward.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 16,
          "questionDetails": "If my brother or sister fails, I feel responsible.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 17,
          "questionDetails": "I often have the feeling that my relationships with others are more important than my own accomplishments.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 18,
          "questionDetails": "Speaking up during a class (or a meeting) is not a problem for me.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 19,
          "questionDetails": "I would offer my seat in a bus to my professor (or my boss).",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 20,
          "questionDetails": "I act the same way no matter who I am with.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 21,
          "questionDetails": "My happiness depends on the happiness of those around me.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 22,
          "questionDetails": "I value being in good health above everything.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 23,
          "questionDetails": "I will stay in a group if they need me, even when I am not happy with the group.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 24,
          "questionDetails": "I try to do what is best for me, regardless of how that might affect others.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 25,
          "questionDetails": "Being able to take care of myself is a primary concern for me.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 26,
          "questionDetails": "It is important to me to respect decisions made by the group.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 27,
          "questionDetails": "My personal identity, independent of others, is very important to me.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 28,
          "questionDetails": "It is important for me to maintain harmony within my group.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "IND",
          "questionNumber": 29,
          "questionDetails": "I act the same way at home that I do at school (or work).",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        },
        {
          "personalityTrait": "INT",
          "questionNumber": 30,
          "questionDetails": "I usually go along with what others want to do, even when I would rather do something different.",
          "answerA": "Strongly Disagree",
          "answerAPoints": 1,
          "answerB": "Disagree",
          "answerBPoints": 2,
          "answerC": "Somewhat Disagree",
          "answerCPoints": 3,
          "answerD": "Don't Agree",
          "answerDPoints": 4,
          "answerE": "Somewhat Agree",
          "answerEPoints": 5,
          "answerF": "Agree",
          "answerFPoints": 6,
          "answerG": "Strongly Agree",
          "answerGPoints": 7
        }
      ]